os:
- linux
services:
- docker
language: node_js
node_js:
- 4.5.0
jdk:
- oraclejdk8
cache:
  directories:
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/app/node_modules"
  - "$HOME/app/node"
env:
  global:
  - PROFILE=dev
  - RUN_APP=1
  - PROTRACTOR=0
  - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
  - JHIPSTER_INSTALL=$JHIPSTER_TRAVIS/install
  - JHIPSTER_SAMPLES=$JHIPSTER_TRAVIS/samples
  - JHIPSTER_SCRIPTS=$JHIPSTER_TRAVIS/scripts
  matrix:
  - JHIPSTER=app-default-from-scratch JHIPSTER_NODE_CACHE=0 PROTRACTOR=1
  - JHIPSTER=app-gradle-hazelcast PROTRACTOR=1
  - JHIPSTER=app-noi18n PROTRACTOR=1
before_install:
- chmod +x $JHIPSTER_INSTALL/02-install-jhipster-stack.sh
- chmod +x $JHIPSTER_INSTALL/03-checkVersion.sh
- chmod +x $JHIPSTER_INSTALL/04-cache.sh
install:
- $JHIPSTER_INSTALL/02-install-jhipster-stack.sh
- $JHIPSTER_INSTALL/03-checkVersion.sh
- $JHIPSTER_INSTALL/04-cache.sh
before_script:
- chmod +x $JHIPSTER_SCRIPTS/01-generate-project.sh
- chmod +x $JHIPSTER_SCRIPTS/02-generate-stormpath.sh
- chmod +x $JHIPSTER_SCRIPTS/03-tests.sh
- chmod +x $JHIPSTER_SCRIPTS/04-run.sh
script:
- $JHIPSTER_SCRIPTS/01-generate-project.sh
- $JHIPSTER_SCRIPTS/02-generate-stormpath.sh
- $JHIPSTER_SCRIPTS/03-tests.sh
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- $JHIPSTER_SCRIPTS/04-run.sh
